site_name: robodm
site_description: An Efficient and Scalable Data Collection and Management Framework For Robotics Learning
site_url: https://github.com/BerkeleyAutomation/robodm/

nav:
  - Home: index.md
  - API Reference: api.md

theme:
  name: material
  palette:
    primary: blue
    accent: orange

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          heading_level: 3
          show_source: false