name: Release

on:
  push:
    tags:
      - '*' # Push events to matching any tag
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for changelog generation
          
      - name: Generate Changelog
        run: .github/release_message.sh > release_message.md
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release_message.md

  test-before-deploy:
    name: Test Before Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          
      - name: Install and test
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .[all]
          pytest tests/ -m "not slow and not benchmark" -x
          
  deploy:
    name: Deploy to PyPI
    needs: [release, test-before-deploy]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # For trusted publishing
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          
      - name: Build package
        run: python -m build
        
      - name: Check package
        run: twine check dist/*
        
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
